# Generated by Django 3.2.5 on 2022-05-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True)),
                ('about_us', models.TextField(blank=True, max_length=9999, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
    ]
