# Generated by Django 3.2.5 on 2022-05-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', models.TimeField()),
            ],
        ),
    ]
