# Generated by Django 3.2.5 on 2022-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0002_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name_plural': 'Saat-İletişim-Adres'},
        ),
        migrations.AddField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='contact',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
