# Generated by Django 3.2.5 on 2022-05-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0003_auto_20220527_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=999)),
            ],
            options={
                'verbose_name_plural': 'Saatler',
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
