# Generated by Django 3.2.5 on 2022-05-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0004_auto_20220527_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=999)),
            ],
            options={
                'verbose_name_plural': 'Adres',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=99, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'İletişim bilgileri',
            },
        ),
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ('id',), 'verbose_name_plural': 'Saatler'},
        ),
    ]
