# Generated by Django 3.2.5 on 2022-05-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=99)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Servisler',
            },
        ),
        migrations.CreateModel(
            name='ServicesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.TextField(blank=True, max_length=999, null=True)),
                ('second_text', models.TextField(blank=True, max_length=999, null=True)),
            ],
            options={
                'verbose_name_plural': 'Servis Yazılar',
            },
        ),
    ]
