# Generated by Django 3.2.5 on 2022-05-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0012_auto_20220531_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motion_images/')),
            ],
            options={
                'verbose_name': 'Motion Picture',
                'verbose_name_plural': 'Motion Pictures',
            },
        ),
    ]
