# Generated by Django 3.2.5 on 2022-06-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0014_auto_20220601_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestext',
            name='gray_text',
            field=models.TextField(blank=True, max_length=99, null=True, verbose_name='Gray Text'),
        ),
        migrations.AlterField(
            model_name='servicestext',
            name='first_text',
            field=models.TextField(blank=True, max_length=99, null=True, verbose_name='First Text'),
        ),
        migrations.AlterField(
            model_name='servicestext',
            name='second_text',
            field=models.TextField(blank=True, max_length=99, null=True, verbose_name='Second Text'),
        ),
    ]
