# Generated by Django 3.2.5 on 2022-06-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0016_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=99, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='about_images/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images in About',
            },
        ),
        migrations.AddField(
            model_name='motionpicture',
            name='title',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
