# Generated by Django 3.2.5 on 2022-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0017_auto_20220602_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Main Image at top of the website', max_length=99, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='main_image/')),
            ],
            options={
                'verbose_name': 'Main Image',
                'verbose_name_plural': 'Main Image',
            },
        ),
    ]
