# Generated by Django 3.2.5 on 2022-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0018_topimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
