# Generated by Django 3.2.5 on 2022-06-18 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0020_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, help_text='e-mail address', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='hours',
            field=models.CharField(help_text='ex: Monday-Friday: 08.00-18.30', max_length=99),
        ),
        migrations.AlterField(
            model_name='servicestext',
            name='gray_text',
            field=models.TextField(blank=True, max_length=99, null=True, verbose_name='Gray Small Text'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Video description'),
        ),
    ]
