# Generated by Django 3.2.5 on 2022-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0022_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=123456789, max_length=20),
            preserve_default=False,
        ),
    ]
