# Generated by Django 3.2.5 on 2022-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0026_auto_20220621_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
