# Generated by Django 3.2.5 on 2022-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0028_auto_20220621_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
