# Generated by Django 3.2.5 on 2022-06-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0031_auto_20220622_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visible',
        ),
    ]
